FROM nubs/composer-build:latest

ADD ./src /src
ADD ./tests /tests

RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN composer global require phpunit/phpunit:*
RUN composer global require phpunit/dbunit:*
